Vagrant.configure("2") do |config|

  config.vm.define "env" do |env|
    env.vm.box = "ubuntu/focal64"
    env.vm.hostname = "env"
    env.vm.network :private_network, ip: "192.168.101.10"
    env.vm.synced_folder "./", "/home/vagrant/repo/"
    env.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--name", "env"]
    end
  end

end
